# Generated by Django 2.1.5 on 2019-02-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasif', '0002_auto_20190206_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareas',
            options={'managed': False},
        ),
    ]
